<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anand Pandey">
<meta name="author" content="Katie Hidden">
<meta name="author" content="Akash Chandra">
<meta name="dcterms.date" content="2022-11-15">
<meta name="description" content="An unsupervised learning algorithm ">

<title>K-Means Clustering</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span style="color: #0366D6;">K-Means Clustering</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>

<div>
  <div class="description">
    An unsupervised learning algorithm<br>
    <hr>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Anand Pandey </p>
             <p>Katie Hidden </p>
             <p>Akash Chandra </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 15, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<hr>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>We have often heard of training machine learning models with labeled data. Imagine if there is a massive volume of data with no labels and we want to come up with a scalable approach to process these data and find insights. Difficult as it may seem, this is possible with clustering algorithms like K-Means.</p>
<p>Unsupervised machine learning is a type of algorithm that works on detecting patterns from a dataset when outcomes are not known or labeled. In unsupervised learning models it is not possible to train the algorithm the way we would normally do in case of supervised learning. The main reason for this is the kind of data available - a data set that is not labelled or classified and the algorithm must work on its own without any supervision. An unsupervised algorithm works on discovering the underlying hidden structure, pattern or association of the data and that helps the model in clustering or grouping the data without any human intervention.</p>
<p>The main goal of this paper is to discuss the concept and underlying methodology of one the unsupervised algorithm called K-Means clustering. We will also discuss how K-Means can be leveraged in real time applications like customer segmentation <span class="citation" data-cites="yul2020astudy">(<a href="#ref-yul2020astudy" role="doc-biblioref">Yulin 2020</a>)</span>. In this paper, we will also be discussing various limitations and bottlenecks of K-Means clustering algorithm and would suggest some improved algorithms to overcome these limitations.</p>
<section id="k-means-clustering" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="k-means-clustering"><span class="header-section-number">1.1</span> K-Means Clustering</h2>
<p>K-means clustering is used for grouping similar observations together by minimizing the Euclidean distance between them. It uses “centroids”. Initially, it randomly chooses K different points in the data and assigns every data point to their nearest centroid. Once all of them are assigned, it moves the centroid to the average of points assigned to it. When the assigned centroid stops changing, we get the converged data points in separate clusters.</p>
</section>
<section id="customer-segmentation" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="customer-segmentation"><span class="header-section-number">1.2</span> Customer Segmentation</h2>
<p>Customer segmentation helps divide customers into different groups based on their common set of characteristics (like age, gender, spending habit, credit score, etc.) that helps in targeting those customers for marketing purposes. The primary focus of customer segmentation is to come up with strategies that helps in identifying customers in each category in order to maximize the profit by optimizing the services and products. Its all about connecting the right products with the right consumer keeping business profitability in mind. Most of the segmentation algorithm is based around analyzing what we call RFM - customer recency (i.e.&nbsp;when the customer last visited the store), frequency (i.e.&nbsp;how many times customer bought the products), and monetary (i.e.&nbsp;how much money the customer spent) <span class="citation" data-cites="tab2022kmeans">(<a href="#ref-tab2022kmeans" role="doc-biblioref">Tabianan 2022</a>)</span>.</p>
<p>Customer segmentation is not only helpful for business but also helps customers by providing them information relevant to their needs. If customers receive too much information which is not related to their regular purchase or their interest on the products, it can cause confusion on deciding their needs. Unnecessary communications might cause customer attrition and may eventually lead to loss in business, revenue and potential customers. The clustering analysis will help to categorize the customer according to their spending habit, purchase habit or specific product or brand the customers interested in. Customer segmentation can be broadly divided into four factors - demographic psychographic, behavioral, and geographic<span class="citation" data-cites="tab2022kmeans">(<a href="#ref-tab2022kmeans" role="doc-biblioref">Tabianan 2022</a>)</span>. In this paper, customer behavioral factor has been primarily focused.</p>
<p><a href="#fig-1">Figure&nbsp;1</a> illustrates the overall process of customer segmentation starting from sourcing the data, selecting the variables, applying the K-Means clustering to creating the marketing strategy for a business.</p>
<center>
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="CustomerSegmentation.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure 1: Customer Segmentation Process (Image Source: ©Anand)</figcaption><p></p>
</figure>
</div>
</center>
<p>K-Means clustering algorithm can help effectively extract groups of customers with similar characteristics and purchasing behavior which in turn helps businesses to specify their differentiated marketing campaign and become more customer-centric.<span class="citation" data-cites="yul2020astudy">(<a href="#ref-yul2020astudy" role="doc-biblioref">Yulin 2020</a>)</span></p>
</section>
<section id="limitations" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="limitations"><span class="header-section-number">1.3</span> Limitations</h2>
<p>One of the challenges of K-means clustering is determining an appropriate number of clusters, or the K-value. While this can be a challenge for datasets of any size, it is especially difficult to determine a reasonable K-value with very large datasets and those with high dimensionality, since it is much more difficult to visualize the data. The K-means clustering algorithm was developed in the 1960s, before the advent of the internet and the resulting era of big data, and as such, it was not designed for datasets of such large scale <span class="citation" data-cites="Sin2020Unsup">(<a href="#ref-Sin2020Unsup" role="doc-biblioref">Sinaga and Yang 2020</a>)</span>.</p>
<p>Another limitation is the algorithm’s tendency to converge to only the local optimum solution, rather than the global minimum. The algorithm is sensitive to the initial centroid values selected, to noise, and to outliers, all of which can cause cluster centers to veer off, resulting in a local minimum solution <span class="citation" data-cites="Jie2020Review">(<a href="#ref-Jie2020Review" role="doc-biblioref">Jie et al. 2020</a>)</span>.</p>
<p>The shape of data clusters is another concern. K-means clustering typically classifies n-hyperspherically shaped data well but is less successful at classifying irregularly shaped clusters <span class="citation" data-cites="Ahmed2020TheK">(<a href="#ref-Ahmed2020TheK" role="doc-biblioref">Ahmed, Seraj, and Islam 2020</a>)</span>.</p>
</section>
<section id="improved-k-means" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="improved-k-means"><span class="header-section-number">1.4</span> Improved K-Means</h2>
<p>Researchers have developed methods to address the limitations of the K-means clustering algorithm.</p>
<p>One popular approach to determining an appropriate K-value is to use the “elbow method”. This method estimates K by calculating the sum of squared error (SSE) for a range of K-values; the SSE values are plotted against the K values. The point before the change in SSE becomes visually minimal (the elbow) is selected as the K-value <span class="citation" data-cites="Nag2022Auto">(<a href="#ref-Nag2022Auto" role="doc-biblioref">Nagaraj et al. 2022</a>)</span>.</p>
<p>To overcome the challenge of selecting a K-value for very large datasets, researchers have developed a “novel unsupervised k-means (U-k-means) clustering algorithm.” This algorithm has a built-in process to determine the K-value and perform K-means clustering using the concept of entropy, and thus does not require any parameter initialization by the user. On the first iteration, the K-value is initialized as the number of data points. Gradually, extra clusters are discarded until the “best” number of clusters is found <span class="citation" data-cites="Sin2020Unsup">(<a href="#ref-Sin2020Unsup" role="doc-biblioref">Sinaga and Yang 2020</a>)</span>.</p>
<p>Other researchers have developed methods utilizing data density to determine the K-value, approximate better initial cluster centroids, and detect outliers. For one proposed variation of the K-means algorithm, first, regional density is calculated using a CLIQUE grid (CLustering In QUEst). In the CLIQUE grid, each dimension is divided into equal parts and the number of data points is calculated within each cell. Cells with counts above a defined threshold are defined as dense units, and adjacent dense units are connected to determine regional density. Noise in areas of low density is removed. Next, a density-based clustering algorithm based on the Clustering by Fast Search and Find of Density Peaks (CFSFDP) algorithm is used to calculate the local density of each point to determine initial cluster centers. This method can be used with datasets of any shape and does not require that a K-value be initialized <span class="citation" data-cites="Xu2020AnImproved">(<a href="#ref-Xu2020AnImproved" role="doc-biblioref">Xu et al. 2020</a>)</span>.</p>
</section>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<p>The methodology for K-Means involve multiple iterations performed with different initial cluster centers or means. However, in each round of the iteration, following steps are performed to achieve convergence<span class="citation" data-cites="ste2008Selective">(<a href="#ref-ste2008Selective" role="doc-biblioref">Stefanowski 2008</a>)</span>:</p>
<ul>
<li>A random selection is made to assign initial centers (Shown as K1, K2 and K3)</li>
<li>Distance between these initial centers and other points are analyzed. Points are assigned to appropriate clusters based on their distance from these center points</li>
<li>New cluster centers are sought by finding the mean of the newly formed clusters. You can see how K1, K2 and K3 are shifting in this step</li>
<li>Steps A, B and C are repeated in multiple iterations until there is no shift detected in the cluster centers K, K2 and K3</li>
</ul>
<a href="#fig-2">Figure&nbsp;2</a> illustrates how the convergence is achieved in K-Means in several iterations.<br>
<br>

<center>
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="kmeans.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure 2: K-Means Convergence Algorithm (Image Source: ©Anand. Inspired from <span class="citation" data-cites="yul2020astudy">(<a href="#ref-yul2020astudy" role="doc-biblioref">Yulin 2020</a>)</span>)</figcaption><p></p>
</figure>
</div>
</center>
<p><br>
</p>
<p>Let’s look at the mathematical implementation of this algorithm <span class="citation" data-cites="yul2020astudy">(<a href="#ref-yul2020astudy" role="doc-biblioref">Yulin 2020</a>)</span>,</p>
<p><strong>Proximity Measures</strong></p>
<p>K-means calculates proximity between data points and centroids to place the data in appropriate cluster. There are several methods to calculate this proximity and the choice of the method plays a critical role in defining the shape of the cluster. <strong><em>Euclidean distance</em></strong> measurement is the most general method used.</p>
<p><span class="math display">\[
D(x, y) = \sqrt{\sum_{i = 1}^{n}{(x_i - y_i)^2}}
\]</span></p>
<p><strong>Algorithm</strong></p>
<p>Suppose there is a dataset D that contains n data points and it was decided that there will be k clusters (and hence k initial cluster centers).</p>
<p><span class="math display">\[
Z_j(I), j = 1, 2, 3,...k.
\]</span></p>
<p>Calculate the Euclidean distance between each data point and the cluster center, <span class="math inline">\(D(x_i, Z_j(I)), i = 1, 2, ...n; j = 1, 2,...k.\)</span>, if below is satisfied:</p>
<p><span class="math display">\[
D(x_i, Z_k(I)) = min{D(x_i, Z_j(I)), j = 1, 2,...n}
\]</span></p>
<p>Now, calculate the new cluster center by calculating the error square sum criterion function <strong>J</strong>: changes</p>
<p><span class="math display">\[
J = \sum_{j = 1}^{k}\sum_{k = 1}^{n_j}||X_k^{(j)}-Z_j(I)||^2
\]</span></p>
</section>
<section id="analysis-and-results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Analysis and Results</h1>
<div class="cell">

</div>
<section id="dataset-description" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="dataset-description"><span class="header-section-number">3.1</span> Dataset Description</h2>
<p>For the customer segmentation, we will be using a data set that contains all the transactions that has occurred for a UK-based non-store online retail between 01/12/2009 and 09/12/2011. The company mainly sells unique all-occasion gift-ware. Many customers of the company are wholesalers. The company was established in 80s as a storefront and relied on direct mailing catalogues and taken order over phone. In recent years, the company launched a website and shifted completely to a web based online retail to take technological advantage of customer-centric targeted marketing approach<span class="citation" data-cites="online2010Chen">(<a href="#ref-online2010Chen" role="doc-biblioref">Chen 2010</a>)</span>.</p>
<p>The customer transactions dataset has 8 variables as shown in below data definition table.</p>
<div class="cell-output-display">

<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>Data Definition</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Attribute </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Type </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Invoice </td>
   <td style="text-align:center;"> Nominal </td>
   <td style="text-align:left;"> Invoice number. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter `c`, it indicates a cancellation. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> StockCode </td>
   <td style="text-align:center;"> Nominal </td>
   <td style="text-align:left;"> Product (item) code. A 5-digit integral number uniquely assigned to each distinct product. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Description </td>
   <td style="text-align:center;"> Nominal </td>
   <td style="text-align:left;"> Product (item) name. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Quantity </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> The quantities of each product (item) per transaction. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> InvoiceDate </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Invoice timestamp. The day and time when a transaction was generated. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Price </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Product price per unit in sterling (£). </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CustomerID </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Customer number. A 5-digit integral number uniquely assigned to each customer. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Country </td>
   <td style="text-align:center;"> Nominal </td>
   <td style="text-align:left;"> Country name. The name of the country where a customer resides. </td>
  </tr>
</tbody>
</table>

</div>
</section>
<section id="load-and-preview-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="load-and-preview-data"><span class="header-section-number">3.2</span> Load and Preview Data</h2>
<p>Load the dataset and summarize column statistics.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-paper lightable-hover" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Invoice </th>
   <th style="text-align:left;"> StockCode </th>
   <th style="text-align:left;"> Description </th>
   <th style="text-align:right;"> Quantity </th>
   <th style="text-align:left;"> InvoiceDate </th>
   <th style="text-align:right;"> Price </th>
   <th style="text-align:right;"> CustomerID </th>
   <th style="text-align:left;"> Country </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 85048 </td>
   <td style="text-align:left;"> 15CM CHRISTMAS GLASS BALL 20 LIGHTS </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 6.95 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 79323P </td>
   <td style="text-align:left;"> PINK CHERRY LIGHTS </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 6.75 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 79323W </td>
   <td style="text-align:left;"> WHITE CHERRY LIGHTS </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 6.75 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 22041 </td>
   <td style="text-align:left;"> RECORD FRAME 7" SINGLE SIZE </td>
   <td style="text-align:right;"> 48 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 2.10 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 21232 </td>
   <td style="text-align:left;"> STRAWBERRY CERAMIC TRINKET BOX </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 489434 </td>
   <td style="text-align:left;"> 22064 </td>
   <td style="text-align:left;"> PINK DOUGHNUT TRINKET POT </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;"> 2009-12-01 07:45:00 </td>
   <td style="text-align:right;"> 1.65 </td>
   <td style="text-align:right;"> 13085 </td>
   <td style="text-align:left;"> United Kingdom </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Let us check the distribution of each field by doing univariate analysis.</p>
<p>Plot:</p>
<ul>
<li>Bar chart for categorical attributes</li>
<li>Histogram for numeric attributes</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the visualizations, we get a good amount of information about the structure of our chosen data. Below are the observations:</p>
<ol type="A">
<li>The Quantity is heavily skewed right and most of the transactions involved a quantity in the range of 1 to 5</li>
<li>The unit Price is also skewed right and most of the items have unit price between 1 and 4</li>
<li>The item with StockCode 85123A was sold most</li>
<li>Most of the customers belong to United Kingdom</li>
</ol>
</section>
<section id="data-preparation" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">3.3</span> Data Preparation</h2>
<p>Before we prepare the data, let’s take a look at the summary and see if there are any missing values or other trends.</p>
<div class="cell-output-display">

<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>Summary of Data</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;">  </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> N </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Missing </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Mean </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> SD </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Min </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Q1 </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Median </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Q3 </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Quantity </td>
   <td style="text-align:center;"> 525461 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:left;"> 10.34 </td>
   <td style="text-align:center;"> 107.42 </td>
   <td style="text-align:center;"> -9600.00 </td>
   <td style="text-align:left;"> 1.00 </td>
   <td style="text-align:center;"> 3.0 </td>
   <td style="text-align:center;"> 10.00 </td>
   <td style="text-align:left;"> 19152.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Price </td>
   <td style="text-align:center;"> 525461 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:left;"> 4.69 </td>
   <td style="text-align:center;"> 146.13 </td>
   <td style="text-align:center;"> -53594.36 </td>
   <td style="text-align:left;"> 1.25 </td>
   <td style="text-align:center;"> 2.1 </td>
   <td style="text-align:center;"> 4.21 </td>
   <td style="text-align:left;"> 25111.09 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer Id </td>
   <td style="text-align:center;"> 417534 </td>
   <td style="text-align:center;"> 107927 </td>
   <td style="text-align:left;"> - </td>
   <td style="text-align:center;"> - </td>
   <td style="text-align:center;"> - </td>
   <td style="text-align:left;"> - </td>
   <td style="text-align:center;"> - </td>
   <td style="text-align:center;"> - </td>
   <td style="text-align:left;"> - </td>
  </tr>
</tbody>
</table>

</div>
<p>For conducting our analysis, we will be applying below listed data pre-processing steps on the original dataset:</p>
<ol type="1">
<li>The CustomerID contains unique Id for each unique Customer. However, we have 107,927 customers with no customer ids. We will be removing these customers before starting our analysis. After removing these customers with no ids, the total records are 417, 534.</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove missing value</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df<span class="ot">=</span><span class="fu">na.omit</span>(df, <span class="at">cols=</span><span class="st">"CustomerID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="2" type="1">
<li>Select appropriate attributes that helps in our analysis - <em>CustomerID</em>, <em>Invoice</em>, <em>Quantity</em>, <em>InvoiceDate</em> and <em>Price</em></li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove description</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Description, Country, StockCode) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="3" type="1">
<li>Create a new attribute <em>Amount</em>. This will help in clustering these customers by the total amount spent. Group the data by customer id to get each unique customer and the total amount spent by them</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Amount <span class="ot">=</span> data<span class="sc">$</span>Quantity <span class="sc">*</span> data<span class="sc">$</span>Price</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>customer_monetary <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Amount =</span> <span class="fu">sum</span>(Amount)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="4" type="1">
<li>Group the data by customer id to get each unique customer and the number of times (<em>Frequency</em>) they visited the store (by counting their number of invoices)</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>customer_frequency <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Invoice =</span> <span class="fu">n</span>()))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(customer_frequency)[<span class="fu">names</span>(customer_frequency) <span class="sc">==</span> <span class="st">"Invoice"</span>] <span class="ot">&lt;-</span> <span class="st">"Frequency"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="5" type="1">
<li>Create a new attribute <em>LastSeen</em>. This will be calculated by subtracting the InvoiceDate from the max (InvoiceDate) and will show how many days have passed since the customer was last seen shopping. Group the data by customer id to get each unique customer and the minimum of the LastSeen.</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>LastSeen <span class="ot">=</span><span class="fu">as.integer</span>(<span class="fu">difftime</span>(<span class="fu">max</span>(data<span class="sc">$</span>InvoiceDate), data<span class="sc">$</span>InvoiceDate, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>customer_lastseen <span class="ot">&lt;-</span>  <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">LastSeen =</span> <span class="fu">min</span>(LastSeen)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="6" type="1">
<li>Merge the above data frames to get unique customer and their total amount, frequency of visit to the store and the LastSeen shopping in the store</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">merge</span>(customer_monetary, customer_frequency, <span class="at">by =</span> <span class="st">'CustomerID'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">merge</span>(customer, customer_lastseen, <span class="at">by =</span> <span class="st">'CustomerID'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="7" type="1">
<li>Detect outliers and remove them. To create meaningful clusters, we will be removing outliers from numeric columns Amount, Invoice and LastSeen</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">melt</span>(customer[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>variable, <span class="at">y=</span>value)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>variable), <span class="at">outlier.colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Above graph shows that there are outliers that need to be addressed to get accurate clustering results.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create detect outlier function</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>detect_outlier <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate first quantile</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    Quantile1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span>.<span class="dv">25</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate third quantile</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    Quantile3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span>.<span class="dv">75</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate inter quartile range</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    IQR <span class="ot">=</span> Quantile3<span class="sc">-</span>Quantile1</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># return true or false</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    x <span class="sc">&gt;</span> Quantile3 <span class="sc">+</span> (IQR<span class="sc">*</span><span class="fl">1.5</span>) <span class="sc">|</span> x <span class="sc">&lt;</span> Quantile1 <span class="sc">-</span> (IQR<span class="sc">*</span><span class="fl">1.5</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># create remove outlier function</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>remove_outlier <span class="ot">&lt;-</span> <span class="cf">function</span>(dataframe,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                            <span class="at">columns=</span><span class="fu">names</span>(dataframe)) {</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># for loop to traverse in columns vector</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (col <span class="cf">in</span> columns) {</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># remove observation if it satisfies outlier function</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        dataframe <span class="ot">&lt;-</span> dataframe[<span class="sc">!</span><span class="fu">detect_outlier</span>(dataframe[[col]]), ]</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(dataframe)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="co"># detect_outlier(customer$Amount)</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">remove_outlier</span>(customer, <span class="fu">c</span>(<span class="st">'Amount'</span>,<span class="st">'Frequency'</span>,<span class="st">'LastSeen'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, after removing outliers and cleaning up the data, we see normal distribution of the Amount, Frequency and LastSeen columns.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">melt</span>(customer[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>variable, <span class="at">y=</span>value)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>variable), <span class="at">outlier.colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="8" type="1">
<li>Scale the data. Since K-Means utilizes the proximity of data points based on Euclidean distance, it is important to reconcile all dimensions into a standard scale.</li>
</ol>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>customer_details <span class="ot">&lt;-</span> customer</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span>  customer <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>CustomerID)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># scale numeric attributes</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>customer_scaled <span class="ot">&lt;-</span> customer <span class="sc">%&gt;%</span> <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"Amount"</span>, <span class="st">"Frequency"</span>, <span class="st">"LastSeen"</span>), <span class="sc">~</span>(<span class="fu">scale</span>(.) <span class="sc">%&gt;%</span> as.vector))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="target-dataset-analysis" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="target-dataset-analysis"><span class="header-section-number">3.4</span> Target Dataset Analysis</h2>
<p>We started our analysis with total 525461 records but after preparing and cleansing the data, we are left with total 3674 records to be analyzed.</p>
<div class="cell-output-display">

<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>Target Data Definition</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Attribute </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Type </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> CustomerID </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Customer number. A 5-digit integral number uniquely assigned to each customer. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Amount </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Total Amount spent by each unique customer </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Frequency </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Number of times customer made purchases bases on their invoice. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LastSeen </td>
   <td style="text-align:center;"> Numeric </td>
   <td style="text-align:left;"> Days elapsed since the customer was last seen shopping. </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>Summary of Target Dataset (3674 Records)</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;">  </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Mean </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Min </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Q1 </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Median </th>
   <th style="text-align:center;font-weight: bold;color: white !important;background-color: #666666 !important;"> Q3 </th>
   <th style="text-align:left;font-weight: bold;color: white !important;background-color: #666666 !important;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Amount </td>
   <td style="text-align:center;"> 776.5 </td>
   <td style="text-align:center;"> -1598.7 </td>
   <td style="text-align:left;"> 241.5 </td>
   <td style="text-align:center;"> 515.1 </td>
   <td style="text-align:center;"> 1091.4 </td>
   <td style="text-align:left;"> 3685.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Frequency </td>
   <td style="text-align:center;"> 48.15 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:left;"> 15.0 </td>
   <td style="text-align:center;"> 34.0 </td>
   <td style="text-align:center;"> 70.0 </td>
   <td style="text-align:left;"> 183.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LastSeen </td>
   <td style="text-align:center;"> 101.8 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:left;"> 23.0 </td>
   <td style="text-align:center;"> 62.0 </td>
   <td style="text-align:center;"> 163.0 </td>
   <td style="text-align:left;"> 373.0 </td>
  </tr>
</tbody>
</table>

</div>
</section>
<section id="statistical-modeling" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="statistical-modeling"><span class="header-section-number">3.5</span> Statistical Modeling</h2>
<section id="optimal-number-of-clusters-k" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="optimal-number-of-clusters-k"><span class="header-section-number">3.5.1</span> Optimal Number of Clusters (K)</h3>
<p>One of the challenges in the K-Means clustering is determining initial value of K to ensure the resulting solution actually represents the underlying structure in the data. The reliability and the performance of a clustering algorithm is directly affected by the initial choice of the number of clusters (K).</p>
<section id="elbow-method" class="level4" data-number="3.5.1.1">
<h4 data-number="3.5.1.1" class="anchored" data-anchor-id="elbow-method"><span class="header-section-number">3.5.1.1</span> Elbow Method</h4>
<p>We will be using a popular method called <em>Elbow Method</em> to determine the optimal value of K. The underlying idea behind this method is that it calculates values of cost with changing K. As the value of K increases, the cluster will have fewer data points and the distortion (within cluster sum of square) will decrease. The larger number of clusters (and hence the lesser number of data points within the cluster) implies the data points are closer to the centroid. So, the point where this distortion declines the most is the elbow point.<span class="citation" data-cites="ste2011Choosing">(<a href="#ref-ste2011Choosing" role="doc-biblioref">STEINLEY 2011</a>)</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(customer_scaled, kmeans, <span class="at">method =</span> <span class="st">"wss"</span>) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">3</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Elbow Method"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="silhouette-method" class="level4" data-number="3.5.1.2">
<h4 data-number="3.5.1.2" class="anchored" data-anchor-id="silhouette-method"><span class="header-section-number">3.5.1.2</span> Silhouette Method</h4>
<p>Another way to find the optimal number of clusters in K-Means is Silhouette Method. We will be using it to double check the results we obtained from the above Elbow method. The silhouette method calculates a coefficient (called silhouette coefficient) which is a measure of how similar a data point is within-cluster (cohesion) compared to other clusters (separation).<span class="citation" data-cites="li2013application">(<a href="#ref-li2013application" role="doc-biblioref">Li 2013</a>)</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(customer_scaled, kmeans, <span class="at">method =</span> <span class="st">"silhouette"</span>)<span class="sc">+</span> <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Silhouette Method"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="gap-statistic-method" class="level4" data-number="3.5.1.3">
<h4 data-number="3.5.1.3" class="anchored" data-anchor-id="gap-statistic-method"><span class="header-section-number">3.5.1.3</span> Gap Statistic Method</h4>
<p>The basic idea of the Gap Statistics is to choose the number of K, where the biggest jump in within-cluster distance occurred, based on the overall behavior of uniformly drawn samples.<span class="citation" data-cites="tibs2001Gap">(<a href="#ref-tibs2001Gap" role="doc-biblioref">R. Tibshirani and Hastie 2001</a>)</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gap_stat <span class="ot">&lt;-</span> <span class="fu">clusGap</span>(customer_scaled, <span class="at">FUN =</span> kmeans, <span class="at">nstart =</span> <span class="dv">25</span>, <span class="at">K.max =</span> <span class="dv">10</span>, <span class="at">B =</span> <span class="dv">50</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_gap_stat</span>(gap_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above graphs for Elbow, Silhouette and Gap Statistics methods, we can observe the critical point is at ‘3’. So, we will pick 3 as our k value for number of clusters.</p>
<p><span class="math display">\[
K = 3
\]</span></p>
</section>
</section>
<section id="k-means-model" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="k-means-model"><span class="header-section-number">3.5.2</span> K-Means Model</h3>
<p>Now, we will create the K-Means model with K = 3.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute k-means with k = 3</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>m1.kmean <span class="ot">&lt;-</span> customer_scaled <span class="sc">%&gt;%</span> <span class="fu">kmeans</span>(k, <span class="at">iter.max =</span> <span class="dv">20</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co">#nstart option that attempts multiple initial configurations and reports on the best one</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Add Clusters to the original dataframe</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>customer<span class="sc">$</span>Cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(m1.kmean<span class="sc">$</span>cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The model results in 3 clusters as was decided and the clusters are formed with sizes 1807, 953, 914.</p>
<p>Now, we can extract the clusters and add to our initial data to do some descriptive statistics at the cluster level. Below table summarizes the original dataset grouped by clusters to show the mean of the variables:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>clustStats <span class="ot">&lt;-</span> customer <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Cluster) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="st">"mean"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>clustStats <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_paper</span>(<span class="st">"hover"</span>, <span class="at">full_width =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class=" lightable-paper lightable-hover" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Cluster </th>
   <th style="text-align:right;"> Amount </th>
   <th style="text-align:right;"> Frequency </th>
   <th style="text-align:right;"> LastSeen </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:right;"> 514.2098 </td>
   <td style="text-align:right;"> 32.46375 </td>
   <td style="text-align:right;"> 51.45102 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:right;"> 309.8873 </td>
   <td style="text-align:right;"> 21.64953 </td>
   <td style="text-align:right;"> 251.48478 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:right;"> 1781.5403 </td>
   <td style="text-align:right;"> 106.80197 </td>
   <td style="text-align:right;"> 45.15536 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above graph shows the clusters created using all columns of customer dataframe using the first two principle components to define the X-Y coordinates of each observation.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"LastSeen"</span>,<span class="st">"Amount"</span>),</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above graph shows that the clusters 1 and 3 are seen in the store often. Cluster 3 customers are spending more whenever they visit. Cluster 2 not seen recently so spend less.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"Frequency"</span>,<span class="st">"Amount"</span>),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above graph shows that the Cluster 3 are more frequently buying and hence spending more. Cluster 1 and 2 are almost having similar trends in terms of number of purchases and amount spent.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"LastSeen"</span>,<span class="st">"Frequency"</span>),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>), </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>             )       </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above graph shows that the Cluster 1 and 3 are seen buying often and whenever they are seen buying, they make lot of purchases.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#9f00e6"</span>, <span class="st">"#e69f00"</span>, <span class="st">"#00e69f"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> colors[<span class="fu">as.numeric</span>(m1.kmean<span class="sc">$</span>cluster)]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>s3d <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(customer_scaled, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">color=</span>colors)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"top"</span>,<span class="at">legend =</span> <span class="fu">paste</span>(<span class="st">"Cluster"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span>  <span class="fu">c</span>(<span class="st">"#9f00e6"</span>, <span class="st">"#e69f00"</span>, <span class="st">"#00e69f"</span>), <span class="at">pch =</span> <span class="dv">16</span>)    </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>centers <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(m1.kmean<span class="sc">$</span>centers)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>s3dp <span class="ot">&lt;-</span> s3d<span class="sc">$</span><span class="fu">points3d</span>(centers,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#000000"</span>,<span class="st">"#0e0a00"</span>,<span class="st">"#000e0a"</span>), <span class="at">type =</span> <span class="st">"h"</span>, <span class="at">pch =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above graph that depicts all the three dimensions of the clustering, we can clearly see that the customers in cluster 3 are seen shopping often, they spend more, and they purchase frequently.</p>
<p>Customers in cluster 2 are of concern. They do not visit the website often but spend almost similar to cluster 1 and also purchase as frequently as cluster 1. So, we can either target cluster 1 to make them buy when they visit store (since they are visiting often but buying less) or make cluster 2 visit often as they are buying more when they visit but visiting less.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>Amount, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()<span class="sc">+</span>  <span class="fu">theme_classic</span>()  <span class="sc">+</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on Amount Spent"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Customers in Cluster# 3 are spending more whereas cluster 2 customers are spending the least.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>Frequency, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on Number of transactions"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Customers in Cluster# 3 are most frequent customers indicating that the frequent customers spend the most.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>LastSeen, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on customer last seen shopping"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Customers in Cluster 2 have not been seen shopping recently. The most recently seen shoppers are in Cluster 3 and that also explains why they have spent more money and bought frequently.</p>
</section>
<section id="analysis" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="analysis"><span class="header-section-number">3.5.3</span> Analysis</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="RFM.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Image Source: ©Anand</figcaption><p></p>
</figure>
</div>
<p>For this business, it is a matter of concern that most of their customers (49%) are not finding what they want. The shop would need to revisit their strategy of what brand/item they should be selling in the online shop to convert visits into revenue.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusion</h1>
<p>For businesses, the customer segmentation play pivotal role in identifying the customers by grouping them based on their buying habits and patterns. With increasingly large volume of transactions and unprecedented business activities, a clustering algorithm like K-Means is a great tool to achieve the segmentation of customers with speed and accuracy. In this paper, we have tried a real-time online business data to show how K-Means helped the business in identifying customers who are at risk of switching to other stores. We have also explained that there are multiple steps in the data mining processes and it started with data selection, then to data preparation, visualization, and finally to model creation and interpretation.</p>
<p>We also understand that K-Means is not always accurate and is dependent on initial choice of centroids and optimal number of clusters chosen. However, there are some improved algorithms that can help overcome these shortcomings.</p>
</section>
<section id="references" class="level1" data-number="5">

<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">5 References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Ahmed2020TheK" class="csl-entry" role="doc-biblioentry">
Ahmed, Mohiuddin, Raihan Seraj, and Syed Mohammed Shamsul Islam. 2020. <span>“The k-Means Algorithm: A Comprehensive Survey and Performance Evaluation.”</span> <em>Electronics</em> 9 (8). <a href="https://doi.org/10.3390/electronics9081295">https://doi.org/10.3390/electronics9081295</a>.
</div>
<div id="ref-online2010Chen" class="csl-entry" role="doc-biblioentry">
Chen, Dr. Daqing. 2010. <span>“Online Retail II Data Set.”</span> School of Engineering, London South Bank University, London SE1 0AA, UK. <a href="https://archive.ics.uci.edu/ml/datasets/Online+Retail+II">https://archive.ics.uci.edu/ml/datasets/Online+Retail+II</a>.
</div>
<div id="ref-Jie2020Review" class="csl-entry" role="doc-biblioentry">
Jie, Chen, Zhang Jiyue, Wu Junhui, Wu Yusheng, Si Huiping, and Lin Kaiyan. 2020. <span>“Review on the Research of k-Means Clustering Algorithm in Big Data.”</span> In <em>2020 IEEE 3rd International Conference on Electronics and Communication Engineering (ICECE)</em>, 107–11. <a href="https://doi.org/10.1109/ICECE51594.2020.9353036">https://doi.org/10.1109/ICECE51594.2020.9353036</a>.
</div>
<div id="ref-li2013application" class="csl-entry" role="doc-biblioentry">
Li, G. 2013. <span>“Application of Improved k-Means Clustering Algorithm in Customer Segmentation.”</span> <em>Applied Mechanics and Materials</em> 411 (414): 1081–84. <a href="https://doi.org/10.4028/www.scientific.net/AMM.411-414.1081">https://doi.org/10.4028/www.scientific.net/AMM.411-414.1081</a>.
</div>
<div id="ref-Nag2022Auto" class="csl-entry" role="doc-biblioentry">
Nagaraj, P, S Selva Birunda, R Venkatesh, V Muneeswaran, S Krishna Narayanan, U Dhannu Shree, and B Sunethra. 2022. <span>“Automatic and Adaptive Segmentation of Customer in r Framework Using k-Means Clustering Technique.”</span> In <em>2022 International Conference on Computer Communication and Informatics (ICCCI)</em>, 1–5. <a href="https://doi.org/10.1109/ICCCI54379.2022.9741067">https://doi.org/10.1109/ICCCI54379.2022.9741067</a>.
</div>
<div id="ref-tibs2001Gap" class="csl-entry" role="doc-biblioentry">
R. Tibshirani, G. Walther, and T. Hastie. 2001. <span>“Estimating the Number of Clusters in a Data Set via Gap Statistic.”</span> <em>Journal of the Royal Statistical Society. Series B, Statistical Methodology</em> 63 (2): 411–23. <a href="https://doi.org/10.1111/1467-9868.00293">https://doi.org/10.1111/1467-9868.00293</a>.
</div>
<div id="ref-Sin2020Unsup" class="csl-entry" role="doc-biblioentry">
Sinaga, Kristina P., and Miin-Shen Yang. 2020. <span>“Unsupervised k-Means Clustering Algorithm.”</span> <em>IEEE Access</em> 8: 80716–27. <a href="https://doi.org/10.1109/ACCESS.2020.2988796">https://doi.org/10.1109/ACCESS.2020.2988796</a>.
</div>
<div id="ref-ste2008Selective" class="csl-entry" role="doc-biblioentry">
Stefanowski, S., &amp; Wilk. 2008. <span>“Selective Pre-Processing of Imbalanced Data for Improving Classification Performance.”</span> <em>Data Warehousing and Knowledge Discovery</em>, 283–92. <a href="https://doi.org/10.1007/978-3-540-85836-2_27">https://doi.org/10.1007/978-3-540-85836-2_27</a>.
</div>
<div id="ref-ste2011Choosing" class="csl-entry" role="doc-biblioentry">
STEINLEY, M. J, &amp; BRUSCO. 2011. <span>“Choosing the Number of Clusters in k-Means Clustering.”</span> <em>Psychological Methods</em> 16 (3): 285–97.
</div>
<div id="ref-tab2022kmeans" class="csl-entry" role="doc-biblioentry">
Tabianan, S., Velu. 2022. <span>“K-Means Clustering Approach for Intelligent Customer Segmentation Using Customer Purchase Behavior Data.”</span> <em>Analytical Methods</em> 14 (12): 7243. <a href="https://doi.org/10.3390/su14127243">https://doi.org/10.3390/su14127243</a>.
</div>
<div id="ref-Xu2020AnImproved" class="csl-entry" role="doc-biblioentry">
Xu, Hui, Shunyu Yao, Qianyun Li, and Zhiwei Ye. 2020. <span>“An Improved k-Means Clustering Algorithm.”</span> In <em>2020 IEEE 5th International Symposium on Smart and Wireless Systems Within the Conferences on Intelligent Data Acquisition and Advanced Computing Systems (IDAACS-SWS)</em>, 1–5. <a href="https://doi.org/10.1109/IDAACS-SWS50031.2020.9297060">https://doi.org/10.1109/IDAACS-SWS50031.2020.9297060</a>.
</div>
<div id="ref-yul2020astudy" class="csl-entry" role="doc-biblioentry">
Yulin, &amp; Qianying, D. 2020. <span>“A Study on e-Commerce Customer Segmentation Management Based on Improved k-Means Algorithm.”</span> <em>Information Systems and e-Business Management</em> 18 (4): 497–510. <a href="https://doi.org/10.1007/s10257-018-0381-3">https://doi.org/10.1007/s10257-018-0381-3</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb24" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "&lt;span style='color: #0366D6;'&gt;K-Means Clustering&lt;/span&gt;"</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> |</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">  An unsupervised learning algorithm&lt;br/&gt;&lt;hr/&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">  - Anand Pandey</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">  - Katie Hidden</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">  - Akash Chandra</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> '`r Sys.Date()`'</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-block-bg: true</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-block-border-left: "#31BAE9"</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="an">course:</span><span class="co"> STA 6257 - Advance Statistical Modeling</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="an">indent:</span><span class="co"> true</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>------</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>We have often heard of training machine learning models with labeled data. Imagine if there is a massive volume of data with no labels and we want to come up with a scalable approach to process these data and find insights. Difficult as it may seem, this is possible with clustering algorithms like K-Means.</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>Unsupervised machine learning is a type of algorithm that works on detecting patterns from a dataset when outcomes are not known or labeled. In unsupervised learning models it is not possible to train the algorithm the way we would normally do in case of supervised learning. The main reason for this is the kind of data available - a data set that is not labelled or classified and the algorithm must work on its own without any supervision. An unsupervised algorithm works on discovering the underlying hidden structure, pattern or association of the data and that helps the model in clustering or grouping the data without any human intervention.</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>The main goal of this paper is to discuss the concept and underlying methodology of one the unsupervised algorithm called K-Means clustering. We will also discuss how K-Means can be leveraged in real time applications like customer segmentation <span class="co">[</span><span class="ot">@yul2020astudy</span><span class="co">]</span>. In this paper, we will also be discussing various limitations and bottlenecks of K-Means clustering algorithm and would suggest some improved algorithms to overcome these limitations.</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## K-Means Clustering</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>K-means clustering is used for grouping similar observations together by minimizing the Euclidean distance between them. It uses “centroids”. Initially, it randomly chooses K different points in the data and assigns every data point to their nearest centroid. Once all of them are assigned, it moves the centroid to the average of points assigned to it. When the assigned centroid stops changing, we get the converged data points in separate clusters.</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Customer Segmentation</span></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>Customer segmentation helps divide customers into different groups based on their common set of characteristics (like age, gender, spending habit, credit score, etc.) that helps in targeting those customers for marketing purposes. The primary focus of customer segmentation is to come up with strategies that helps in identifying customers in each category in order to maximize the profit by optimizing the services and products. Its all about connecting the right products with the right consumer keeping business profitability in mind. Most of the segmentation algorithm is based around analyzing what we call RFM - customer recency (i.e. when the customer last visited the store), frequency (i.e. how many times customer bought the products), and monetary (i.e. how much money the customer spent) <span class="co">[</span><span class="ot">@tab2022kmeans</span><span class="co">]</span>.</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>Customer segmentation is not only helpful for business but also helps customers by providing them information relevant to their needs. If customers receive too much information which is not related to their regular purchase or their interest on the products, it can cause confusion on deciding their needs. Unnecessary communications might cause customer attrition and may eventually lead to loss in business, revenue and potential customers. The clustering analysis will help to categorize the customer according to their spending habit, purchase habit or specific product or brand the customers interested in. Customer segmentation can be broadly divided into four factors - demographic psychographic, behavioral, and geographic<span class="co">[</span><span class="ot">@tab2022kmeans</span><span class="co">]</span>. In this paper, customer behavioral factor has been primarily focused.</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>@fig-1 illustrates the overall process of customer segmentation starting from sourcing the data, selecting the variables, applying the K-Means clustering to creating the marketing strategy for a business.</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;center&gt;</span></span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a><span class="al">![Customer Segmentation Process (Image Source: ©Anand)](CustomerSegmentation.png)</span>{#fig-1}</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;/center&gt;</span></span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>K-Means clustering algorithm can help effectively extract groups of customers with similar characteristics and purchasing behavior which in turn helps businesses to specify their differentiated marketing campaign and become more customer-centric.<span class="co">[</span><span class="ot">@yul2020astudy</span><span class="co">]</span></span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations</span></span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>One of the challenges of K-means clustering is determining an appropriate number of clusters, or the K-value. While this can be a challenge for datasets of any size, it is especially difficult to determine a reasonable K-value with very large datasets and those with high dimensionality, since it is much more difficult to visualize the data. The K-means clustering algorithm was developed in the 1960s, before the advent of the internet and the resulting era of big data, and as such, it was not designed for datasets of such large scale <span class="co">[</span><span class="ot">@Sin2020Unsup</span><span class="co">]</span>.</span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>Another limitation is the algorithm’s tendency to converge to only the local optimum solution, rather than the global minimum. The algorithm is sensitive to the initial centroid values selected, to noise, and to outliers, all of which can cause cluster centers to veer off, resulting in a local minimum solution <span class="co">[</span><span class="ot">@Jie2020Review</span><span class="co">]</span>.</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>The shape of data clusters is another concern. K-means clustering typically classifies n-hyperspherically shaped data well but is less successful at classifying irregularly shaped clusters <span class="co">[</span><span class="ot">@Ahmed2020TheK</span><span class="co">]</span>.</span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## Improved K-Means</span></span>
<span id="cb24-61"><a href="#cb24-61" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-62"><a href="#cb24-62" aria-hidden="true" tabindex="-1"></a>Researchers have developed methods to address the limitations of the K-means clustering algorithm.</span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a>One popular approach to determining an appropriate K-value is to use the “elbow method”. This method estimates K by calculating the sum of squared error (SSE) for a range of K-values; the SSE values are plotted against the K values. The point before the change in SSE becomes visually minimal (the elbow) is selected as the K-value <span class="co">[</span><span class="ot">@Nag2022Auto</span><span class="co">]</span>.</span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>To overcome the challenge of selecting a K-value for very large datasets, researchers have developed a “novel unsupervised k-means (U-k-means) clustering algorithm.” This algorithm has a built-in process to determine the K-value and perform K-means clustering using the concept of entropy, and thus does not require any parameter initialization by the user. On the first iteration, the K-value is initialized as the number of data points. Gradually, extra clusters are discarded until the “best” number of clusters is found <span class="co">[</span><span class="ot">@Sin2020Unsup</span><span class="co">]</span>.</span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>Other researchers have developed methods utilizing data density to determine the K-value, approximate better initial cluster centroids, and detect outliers. For one proposed variation of the K-means algorithm, first, regional density is calculated using a CLIQUE grid (CLustering In QUEst). In the CLIQUE grid, each dimension is divided into equal parts and the number of data points is calculated within each cell. Cells with counts above a defined threshold are defined as dense units, and adjacent dense units are connected to determine regional density. Noise in areas of low density is removed. Next, a density-based clustering algorithm based on the Clustering by Fast Search and Find of Density Peaks (CFSFDP) algorithm is used to calculate the local density of each point to determine initial cluster centers. This method can be used with datasets of any shape and does not require that a K-value be initialized <span class="co">[</span><span class="ot">@Xu2020AnImproved</span><span class="co">]</span>.</span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a><span class="fu"># Methods</span></span>
<span id="cb24-72"><a href="#cb24-72" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-73"><a href="#cb24-73" aria-hidden="true" tabindex="-1"></a>The methodology for K-Means involve multiple iterations performed with different initial cluster centers or means. However, in each round of the iteration, following steps are performed to achieve convergence<span class="co">[</span><span class="ot">@ste2008Selective</span><span class="co">]</span>:</span>
<span id="cb24-74"><a href="#cb24-74" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-75"><a href="#cb24-75" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>A random selection is made to assign initial centers (Shown as K1, K2 and K3)</span>
<span id="cb24-76"><a href="#cb24-76" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Distance between these initial centers and other points are analyzed. Points are assigned to appropriate clusters based on their distance from these center points</span>
<span id="cb24-77"><a href="#cb24-77" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>New cluster centers are sought by finding the mean of the newly formed clusters. You can see how K1, K2 and K3 are shifting in this step</span>
<span id="cb24-78"><a href="#cb24-78" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Steps A, B and C are repeated in multiple iterations until there is no shift detected in the cluster centers K, K2 and K3</span>
<span id="cb24-79"><a href="#cb24-79" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-80"><a href="#cb24-80" aria-hidden="true" tabindex="-1"></a>@fig-2 illustrates how the convergence is achieved in K-Means in several iterations.</span>
<span id="cb24-81"><a href="#cb24-81" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb24-82"><a href="#cb24-82" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb24-83"><a href="#cb24-83" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;center&gt;</span></span>
<span id="cb24-84"><a href="#cb24-84" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">K-Means Convergence Algorithm (Image Source: ©Anand. Inspired from [@yul2020astudy])</span><span class="co">](kmeans.png)</span>{#fig-2}</span>
<span id="cb24-85"><a href="#cb24-85" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;/center&gt;</span></span>
<span id="cb24-86"><a href="#cb24-86" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb24-87"><a href="#cb24-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-88"><a href="#cb24-88" aria-hidden="true" tabindex="-1"></a>Let's look at the mathematical implementation of this algorithm <span class="co">[</span><span class="ot">@yul2020astudy</span><span class="co">]</span>,</span>
<span id="cb24-89"><a href="#cb24-89" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-90"><a href="#cb24-90" aria-hidden="true" tabindex="-1"></a>**Proximity Measures**</span>
<span id="cb24-91"><a href="#cb24-91" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-92"><a href="#cb24-92" aria-hidden="true" tabindex="-1"></a>K-means calculates proximity between data points and centroids to place the data in appropriate cluster. There are several methods to calculate this proximity and the choice of the method plays a critical role in defining the shape of the cluster. **_Euclidean distance_** measurement is the most general method used.</span>
<span id="cb24-93"><a href="#cb24-93" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-94"><a href="#cb24-94" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-95"><a href="#cb24-95" aria-hidden="true" tabindex="-1"></a>D(x, y) = \sqrt{\sum_{i = 1}^{n}{(x_i - y_i)^2}}</span>
<span id="cb24-96"><a href="#cb24-96" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-97"><a href="#cb24-97" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-98"><a href="#cb24-98" aria-hidden="true" tabindex="-1"></a>**Algorithm**</span>
<span id="cb24-99"><a href="#cb24-99" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-100"><a href="#cb24-100" aria-hidden="true" tabindex="-1"></a>Suppose there is a dataset D that contains n data points and it was decided that there will be k clusters (and hence k initial cluster centers).</span>
<span id="cb24-101"><a href="#cb24-101" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-102"><a href="#cb24-102" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-103"><a href="#cb24-103" aria-hidden="true" tabindex="-1"></a>Z_j(I), j = 1, 2, 3,...k.</span>
<span id="cb24-104"><a href="#cb24-104" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-105"><a href="#cb24-105" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-106"><a href="#cb24-106" aria-hidden="true" tabindex="-1"></a>Calculate the Euclidean distance between each data point and the cluster center, $D(x_i, Z_j(I)), i = 1, 2, ...n; j = 1, 2,...k.$, if below is satisfied:</span>
<span id="cb24-107"><a href="#cb24-107" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-108"><a href="#cb24-108" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-109"><a href="#cb24-109" aria-hidden="true" tabindex="-1"></a>D(x_i, Z_k(I)) = min{D(x_i, Z_j(I)), j = 1, 2,...n}</span>
<span id="cb24-110"><a href="#cb24-110" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-111"><a href="#cb24-111" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-112"><a href="#cb24-112" aria-hidden="true" tabindex="-1"></a>Now, calculate the new cluster center by calculating the error square sum criterion function **J**:</span>
<span id="cb24-113"><a href="#cb24-113" aria-hidden="true" tabindex="-1"></a>changes</span>
<span id="cb24-114"><a href="#cb24-114" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-115"><a href="#cb24-115" aria-hidden="true" tabindex="-1"></a>J = \sum_{j = 1}^{k}\sum_{k = 1}^{n_j}||X_k^{(j)}-Z_j(I)||^2</span>
<span id="cb24-116"><a href="#cb24-116" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-117"><a href="#cb24-117" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-118"><a href="#cb24-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-119"><a href="#cb24-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-120"><a href="#cb24-120" aria-hidden="true" tabindex="-1"></a><span class="fu"># Analysis and Results</span></span>
<span id="cb24-121"><a href="#cb24-121" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-122"><a href="#cb24-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-123"><a href="#cb24-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=FALSE, message=FALSE}</span></span>
<span id="cb24-124"><a href="#cb24-124" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'readxl'</span>)) {</span>
<span id="cb24-125"><a href="#cb24-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'readxl'</span>)</span>
<span id="cb24-126"><a href="#cb24-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb24-127"><a href="#cb24-127" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-128"><a href="#cb24-128" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'papeR'</span>)){</span>
<span id="cb24-129"><a href="#cb24-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'papeR'</span>)</span>
<span id="cb24-130"><a href="#cb24-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'papeR'</span>)</span>
<span id="cb24-131"><a href="#cb24-131" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-132"><a href="#cb24-132" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'Hmisc'</span>)) {</span>
<span id="cb24-133"><a href="#cb24-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'Hmisc'</span>)</span>
<span id="cb24-134"><a href="#cb24-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'Hmisc'</span>)</span>
<span id="cb24-135"><a href="#cb24-135" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-136"><a href="#cb24-136" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'reshape2'</span>)) {</span>
<span id="cb24-137"><a href="#cb24-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'reshape2'</span>)</span>
<span id="cb24-138"><a href="#cb24-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'reshape2'</span>)</span>
<span id="cb24-139"><a href="#cb24-139" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-140"><a href="#cb24-140" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'plotly'</span>)) {</span>
<span id="cb24-141"><a href="#cb24-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'plotly'</span>)</span>
<span id="cb24-142"><a href="#cb24-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'plotly'</span>)</span>
<span id="cb24-143"><a href="#cb24-143" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-144"><a href="#cb24-144" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'factoextra'</span>)) {</span>
<span id="cb24-145"><a href="#cb24-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'factoextra'</span>)</span>
<span id="cb24-146"><a href="#cb24-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'factoextra'</span>)</span>
<span id="cb24-147"><a href="#cb24-147" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-148"><a href="#cb24-148" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'scatterplot3d'</span>)) {</span>
<span id="cb24-149"><a href="#cb24-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'scatterplot3d'</span>)</span>
<span id="cb24-150"><a href="#cb24-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(<span class="st">'scatterplot3d'</span>)</span>
<span id="cb24-151"><a href="#cb24-151" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-152"><a href="#cb24-152" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb24-153"><a href="#cb24-153" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-154"><a href="#cb24-154" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb24-155"><a href="#cb24-155" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb24-156"><a href="#cb24-156" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb24-157"><a href="#cb24-157" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb24-158"><a href="#cb24-158" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xtable)</span>
<span id="cb24-159"><a href="#cb24-159" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb24-160"><a href="#cb24-160" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb24-161"><a href="#cb24-161" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qwraps2)</span>
<span id="cb24-162"><a href="#cb24-162" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb24-163"><a href="#cb24-163" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb24-164"><a href="#cb24-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-165"><a href="#cb24-165" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-166"><a href="#cb24-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-167"><a href="#cb24-167" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dataset Description</span></span>
<span id="cb24-168"><a href="#cb24-168" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-169"><a href="#cb24-169" aria-hidden="true" tabindex="-1"></a>For the customer segmentation, we will be using a data set that contains all the transactions that has occurred for a UK-based non-store online retail between 01/12/2009 and 09/12/2011. The company mainly sells unique all-occasion gift-ware. Many customers of the company are wholesalers. The company was established in 80s as a storefront and relied on direct mailing catalogues and taken order over phone. In recent years, the company launched a website and shifted completely to a web based online retail to take technological advantage of customer-centric targeted marketing approach<span class="co">[</span><span class="ot">@online2010Chen</span><span class="co">]</span>. </span>
<span id="cb24-170"><a href="#cb24-170" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-171"><a href="#cb24-171" aria-hidden="true" tabindex="-1"></a>The customer transactions dataset has 8 variables as shown in below data definition table.</span>
<span id="cb24-172"><a href="#cb24-172" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-173"><a href="#cb24-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-174"><a href="#cb24-174" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, warning=FALSE, results = "asis"}</span></span>
<span id="cb24-175"><a href="#cb24-175" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">vars =</span> <span class="fu">c</span>(<span class="st">'Invoice'</span>, <span class="st">'StockCode'</span>, <span class="st">'Description'</span>, <span class="st">'Quantity'</span>, <span class="st">'InvoiceDate'</span>, <span class="st">'Price'</span>, <span class="st">'CustomerID'</span>, <span class="st">'Country'</span>),</span>
<span id="cb24-176"><a href="#cb24-176" aria-hidden="true" tabindex="-1"></a>               </span>
<span id="cb24-177"><a href="#cb24-177" aria-hidden="true" tabindex="-1"></a>                <span class="at">DataType =</span> <span class="fu">c</span>(<span class="st">'Nominal'</span>, <span class="st">'Nominal'</span>, <span class="st">'Nominal'</span>, <span class="st">'Numeric'</span>, <span class="st">'Numeric'</span>, <span class="st">'Numeric'</span>,<span class="st">'Numeric'</span>,<span class="st">'Nominal'</span>),</span>
<span id="cb24-178"><a href="#cb24-178" aria-hidden="true" tabindex="-1"></a>                <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">'Invoice number. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter `c`, it indicates a cancellation.'</span>,</span>
<span id="cb24-179"><a href="#cb24-179" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Product (item) code. A 5-digit integral number uniquely assigned to each distinct product.'</span>,</span>
<span id="cb24-180"><a href="#cb24-180" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Product (item) name.'</span>,</span>
<span id="cb24-181"><a href="#cb24-181" aria-hidden="true" tabindex="-1"></a>    <span class="st">'The quantities of each product (item) per transaction.'</span>,</span>
<span id="cb24-182"><a href="#cb24-182" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Invoice timestamp. The day and time when a transaction was generated.'</span>,</span>
<span id="cb24-183"><a href="#cb24-183" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Product price per unit in sterling (£).'</span>,</span>
<span id="cb24-184"><a href="#cb24-184" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Customer number. A 5-digit integral number uniquely assigned to each customer.'</span>,</span>
<span id="cb24-185"><a href="#cb24-185" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Country name. The name of the country where a customer resides.'</span>),</span>
<span id="cb24-186"><a href="#cb24-186" aria-hidden="true" tabindex="-1"></a>                <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-187"><a href="#cb24-187" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-188"><a href="#cb24-188" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(a,</span>
<span id="cb24-189"><a href="#cb24-189" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Data Definition"</span>,</span>
<span id="cb24-190"><a href="#cb24-190" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Attribute"</span>, <span class="st">"Type"</span>, <span class="st">"Description"</span>),</span>
<span id="cb24-191"><a href="#cb24-191" aria-hidden="true" tabindex="-1"></a>      <span class="at">align=</span><span class="st">"lcl"</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-192"><a href="#cb24-192" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-193"><a href="#cb24-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> T, <span class="at">background =</span> <span class="st">"#666666"</span>, <span class="at">color =</span> <span class="st">"white"</span>)</span>
<span id="cb24-194"><a href="#cb24-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-195"><a href="#cb24-195" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-196"><a href="#cb24-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-197"><a href="#cb24-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load and Preview Data</span></span>
<span id="cb24-198"><a href="#cb24-198" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-199"><a href="#cb24-199" aria-hidden="true" tabindex="-1"></a>Load the dataset and summarize column statistics.</span>
<span id="cb24-200"><a href="#cb24-200" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-201"><a href="#cb24-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning = FALSE, echo=FALSE}</span></span>
<span id="cb24-202"><a href="#cb24-202" aria-hidden="true" tabindex="-1"></a>filename <span class="ot">&lt;-</span> <span class="st">"online_retail_II.xlsx"</span></span>
<span id="cb24-203"><a href="#cb24-203" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read_excel</span>(filename)</span>
<span id="cb24-204"><a href="#cb24-204" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-205"><a href="#cb24-205" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">'Customer ID'</span>] <span class="ot">&lt;-</span> <span class="st">'CustomerID'</span></span>
<span id="cb24-206"><a href="#cb24-206" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-207"><a href="#cb24-207" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df) <span class="sc">%&gt;%</span></span>
<span id="cb24-208"><a href="#cb24-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-209"><a href="#cb24-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_paper</span>(<span class="st">"hover"</span>, <span class="at">full_width =</span> T)</span>
<span id="cb24-210"><a href="#cb24-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-211"><a href="#cb24-211" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-212"><a href="#cb24-212" aria-hidden="true" tabindex="-1"></a>Let us check the distribution of each field by doing univariate analysis.</span>
<span id="cb24-213"><a href="#cb24-213" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-214"><a href="#cb24-214" aria-hidden="true" tabindex="-1"></a>Plot:</span>
<span id="cb24-215"><a href="#cb24-215" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-216"><a href="#cb24-216" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Bar chart for categorical attributes</span>
<span id="cb24-217"><a href="#cb24-217" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Histogram for numeric attributes</span>
<span id="cb24-218"><a href="#cb24-218" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-219"><a href="#cb24-219" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=FALSE}</span></span>
<span id="cb24-220"><a href="#cb24-220" aria-hidden="true" tabindex="-1"></a>df1<span class="ot">=</span><span class="fu">na.omit</span>(df, <span class="at">cols=</span><span class="st">"CustomerID"</span>)</span>
<span id="cb24-221"><a href="#cb24-221" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>QuantityRange <span class="ot">&lt;-</span> <span class="fu">cut</span>(df1<span class="sc">$</span>Quantity, <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="cn">Inf</span>))</span>
<span id="cb24-222"><a href="#cb24-222" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df1,<span class="fu">aes</span>(QuantityRange))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">stat=</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> ..count..))<span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Quantity Histogram"</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">'Quantity'</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">'Count'</span>)<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span>
<span id="cb24-223"><a href="#cb24-223" aria-hidden="true" tabindex="-1"></a>  <span class="co">#theme(axis.text.x=element_blank(),axis.text.y=element_blank())</span></span>
<span id="cb24-224"><a href="#cb24-224" aria-hidden="true" tabindex="-1"></a><span class="co">#g1</span></span>
<span id="cb24-225"><a href="#cb24-225" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>PriceRange <span class="ot">&lt;-</span> <span class="fu">cut</span>(df1<span class="sc">$</span>Price, <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">50</span>, <span class="cn">Inf</span>))</span>
<span id="cb24-226"><a href="#cb24-226" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df1,<span class="fu">aes</span>(PriceRange))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">stat=</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> ..count..))<span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Price Histogram"</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">'Price'</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">'Count'</span>)<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span>
<span id="cb24-227"><a href="#cb24-227" aria-hidden="true" tabindex="-1"></a>  <span class="co">#theme(axis.text.x=element_blank(),axis.text.y=element_blank())</span></span>
<span id="cb24-228"><a href="#cb24-228" aria-hidden="true" tabindex="-1"></a><span class="co">#g2</span></span>
<span id="cb24-229"><a href="#cb24-229" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-230"><a href="#cb24-230" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span></span>
<span id="cb24-231"><a href="#cb24-231" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(StockCode) <span class="sc">%&gt;%</span></span>
<span id="cb24-232"><a href="#cb24-232" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb24-233"><a href="#cb24-233" aria-hidden="true" tabindex="-1"></a>    <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">wt =</span> count)  <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(StockCode, <span class="sc">-</span>count), <span class="at">y=</span>count, <span class="at">fill=</span>StockCode))<span class="sc">+</span><span class="fu">geom_bar</span>(<span class="at">stat=</span> <span class="st">"identity"</span>)<span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Top 5 StockCode"</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">'StockCode'</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">'Count'</span>)<span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),<span class="at">axis.text.y=</span><span class="fu">element_blank</span>())</span>
<span id="cb24-234"><a href="#cb24-234" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-235"><a href="#cb24-235" aria-hidden="true" tabindex="-1"></a><span class="co">#g3</span></span>
<span id="cb24-236"><a href="#cb24-236" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-237"><a href="#cb24-237" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span></span>
<span id="cb24-238"><a href="#cb24-238" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb24-239"><a href="#cb24-239" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb24-240"><a href="#cb24-240" aria-hidden="true" tabindex="-1"></a>    <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">wt =</span> count) <span class="sc">%&gt;%</span></span>
<span id="cb24-241"><a href="#cb24-241" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(Country, <span class="sc">-</span>count), <span class="at">y=</span>count, <span class="at">fill=</span>Country))<span class="sc">+</span><span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>)<span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Top 5 Country"</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">'Country'</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">'Count'</span>)<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),<span class="at">axis.text.y=</span><span class="fu">element_blank</span>())</span>
<span id="cb24-242"><a href="#cb24-242" aria-hidden="true" tabindex="-1"></a><span class="co">#g4</span></span>
<span id="cb24-243"><a href="#cb24-243" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-244"><a href="#cb24-244" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(g1, g2, g3, g4,</span>
<span id="cb24-245"><a href="#cb24-245" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>),</span>
<span id="cb24-246"><a href="#cb24-246" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb24-247"><a href="#cb24-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-248"><a href="#cb24-248" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-249"><a href="#cb24-249" aria-hidden="true" tabindex="-1"></a>From the visualizations, we get a good amount of information about the structure of our chosen data. Below are the observations:</span>
<span id="cb24-250"><a href="#cb24-250" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-251"><a href="#cb24-251" aria-hidden="true" tabindex="-1"></a>A.    The Quantity is heavily skewed right and most of the transactions involved a quantity in the range of 1 to 5</span>
<span id="cb24-252"><a href="#cb24-252" aria-hidden="true" tabindex="-1"></a>B.    The unit Price is also skewed right and most of the items have unit price between 1 and 4</span>
<span id="cb24-253"><a href="#cb24-253" aria-hidden="true" tabindex="-1"></a>C.    The item with StockCode 85123A was sold most</span>
<span id="cb24-254"><a href="#cb24-254" aria-hidden="true" tabindex="-1"></a>D.    Most of the customers belong to United Kingdom</span>
<span id="cb24-255"><a href="#cb24-255" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-256"><a href="#cb24-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-257"><a href="#cb24-257" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Preparation</span></span>
<span id="cb24-258"><a href="#cb24-258" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-259"><a href="#cb24-259" aria-hidden="true" tabindex="-1"></a>Before we prepare the data, let's take a look at the summary and see if there are any missing values or other trends.</span>
<span id="cb24-260"><a href="#cb24-260" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-261"><a href="#cb24-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, include=F}</span></span>
<span id="cb24-262"><a href="#cb24-262" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span>
<span id="cb24-263"><a href="#cb24-263" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-264"><a href="#cb24-264" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-265"><a href="#cb24-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, warning=FALSE, results = "asis"}</span></span>
<span id="cb24-266"><a href="#cb24-266" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">vars =</span> <span class="fu">c</span>(<span class="st">'Quantity'</span>, <span class="st">'Price'</span>, <span class="st">'Customer Id'</span>),</span>
<span id="cb24-267"><a href="#cb24-267" aria-hidden="true" tabindex="-1"></a>                <span class="at">N =</span> <span class="fu">c</span>(<span class="st">'525461'</span>, <span class="st">'525461'</span>, <span class="st">'417534'</span>),</span>
<span id="cb24-268"><a href="#cb24-268" aria-hidden="true" tabindex="-1"></a>                <span class="at">Missing =</span> <span class="fu">c</span>(<span class="st">'0'</span>,<span class="st">'0'</span>,<span class="st">'107927'</span>),</span>
<span id="cb24-269"><a href="#cb24-269" aria-hidden="true" tabindex="-1"></a>                <span class="at">Mean =</span> <span class="fu">c</span>(<span class="st">'10.34'</span>, <span class="st">'4.69'</span>, <span class="st">'-'</span>),</span>
<span id="cb24-270"><a href="#cb24-270" aria-hidden="true" tabindex="-1"></a>                <span class="at">SD =</span> <span class="fu">c</span>(<span class="st">'107.42'</span>, <span class="st">'146.13'</span>, <span class="st">'-'</span>),</span>
<span id="cb24-271"><a href="#cb24-271" aria-hidden="true" tabindex="-1"></a>                <span class="at">Min =</span> <span class="fu">c</span>(<span class="st">'-9600.00'</span>,<span class="st">'-53594.36'</span>,<span class="st">'-'</span>),</span>
<span id="cb24-272"><a href="#cb24-272" aria-hidden="true" tabindex="-1"></a>                <span class="at">Q1 =</span> <span class="fu">c</span>(<span class="st">'1.00'</span>, <span class="st">'1.25'</span>, <span class="st">'-'</span>),</span>
<span id="cb24-273"><a href="#cb24-273" aria-hidden="true" tabindex="-1"></a>                <span class="at">Median =</span> <span class="fu">c</span>(<span class="st">'3.0'</span>, <span class="st">'2.1'</span>, <span class="st">'-'</span>),</span>
<span id="cb24-274"><a href="#cb24-274" aria-hidden="true" tabindex="-1"></a>                <span class="at">Q3 =</span> <span class="fu">c</span>(<span class="st">'10.00'</span>, <span class="st">'4.21'</span>, <span class="st">'-'</span>),</span>
<span id="cb24-275"><a href="#cb24-275" aria-hidden="true" tabindex="-1"></a>                <span class="at">Max =</span> <span class="fu">c</span>(<span class="st">'19152.00'</span>, <span class="st">'25111.09'</span>,<span class="st">'-'</span>),</span>
<span id="cb24-276"><a href="#cb24-276" aria-hidden="true" tabindex="-1"></a>                <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-277"><a href="#cb24-277" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-278"><a href="#cb24-278" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(a,</span>
<span id="cb24-279"><a href="#cb24-279" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Summary of Data"</span>,</span>
<span id="cb24-280"><a href="#cb24-280" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"N"</span>, <span class="st">"Missing"</span>, <span class="st">"Mean"</span>, <span class="st">"SD"</span>, <span class="st">"Min"</span>, <span class="st">"Q1"</span>, <span class="st">"Median"</span>, <span class="st">"Q3"</span>, <span class="st">"Max"</span>),</span>
<span id="cb24-281"><a href="#cb24-281" aria-hidden="true" tabindex="-1"></a>      <span class="at">align=</span><span class="st">"lcc"</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-282"><a href="#cb24-282" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-283"><a href="#cb24-283" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> T, <span class="at">background =</span> <span class="st">"#666666"</span>, <span class="at">color =</span> <span class="st">"white"</span>)</span>
<span id="cb24-284"><a href="#cb24-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-285"><a href="#cb24-285" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-286"><a href="#cb24-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-287"><a href="#cb24-287" aria-hidden="true" tabindex="-1"></a>For conducting our analysis, we will be applying below listed data pre-processing steps on the original dataset:</span>
<span id="cb24-288"><a href="#cb24-288" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-289"><a href="#cb24-289" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>The CustomerID contains unique Id for each unique Customer. However, we have 107,927 customers with no customer ids. We will be removing these customers before starting our analysis. After removing these customers with no ids, the total records are 417, 534.</span>
<span id="cb24-290"><a href="#cb24-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-291"><a href="#cb24-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-292"><a href="#cb24-292" aria-hidden="true" tabindex="-1"></a><span class="co">#remove missing value</span></span>
<span id="cb24-293"><a href="#cb24-293" aria-hidden="true" tabindex="-1"></a>df<span class="ot">=</span><span class="fu">na.omit</span>(df, <span class="at">cols=</span><span class="st">"CustomerID"</span>)</span>
<span id="cb24-294"><a href="#cb24-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-295"><a href="#cb24-295" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-296"><a href="#cb24-296" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Select appropriate attributes that helps in our analysis - *CustomerID*, *Invoice*, *Quantity*, *InvoiceDate* and *Price*</span>
<span id="cb24-297"><a href="#cb24-297" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-298"><a href="#cb24-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-299"><a href="#cb24-299" aria-hidden="true" tabindex="-1"></a><span class="co">#remove description</span></span>
<span id="cb24-300"><a href="#cb24-300" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Description, Country, StockCode) )</span>
<span id="cb24-301"><a href="#cb24-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-302"><a href="#cb24-302" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-303"><a href="#cb24-303" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Create a new attribute *Amount*. This will help in clustering these customers by the total amount spent. Group the data by customer id to get each unique customer and the total amount spent by them</span>
<span id="cb24-304"><a href="#cb24-304" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-305"><a href="#cb24-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-306"><a href="#cb24-306" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Amount <span class="ot">=</span> data<span class="sc">$</span>Quantity <span class="sc">*</span> data<span class="sc">$</span>Price</span>
<span id="cb24-307"><a href="#cb24-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-308"><a href="#cb24-308" aria-hidden="true" tabindex="-1"></a>customer_monetary <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span></span>
<span id="cb24-309"><a href="#cb24-309" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span></span>
<span id="cb24-310"><a href="#cb24-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Amount =</span> <span class="fu">sum</span>(Amount)))</span>
<span id="cb24-311"><a href="#cb24-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-312"><a href="#cb24-312" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-313"><a href="#cb24-313" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Group the data by customer id to get each unique customer and the number of times (*Frequency*) they visited the store (by counting their number of invoices)</span>
<span id="cb24-314"><a href="#cb24-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-315"><a href="#cb24-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-316"><a href="#cb24-316" aria-hidden="true" tabindex="-1"></a>customer_frequency <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Invoice =</span> <span class="fu">n</span>()))</span>
<span id="cb24-317"><a href="#cb24-317" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-318"><a href="#cb24-318" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(customer_frequency)[<span class="fu">names</span>(customer_frequency) <span class="sc">==</span> <span class="st">"Invoice"</span>] <span class="ot">&lt;-</span> <span class="st">"Frequency"</span></span>
<span id="cb24-319"><a href="#cb24-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-320"><a href="#cb24-320" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-321"><a href="#cb24-321" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Create a new attribute *LastSeen*. This will be calculated by subtracting the InvoiceDate from the max (InvoiceDate) and will show how many days have passed since the customer was last seen shopping. Group the data by customer id to get each unique customer and the minimum of the LastSeen.</span>
<span id="cb24-322"><a href="#cb24-322" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-323"><a href="#cb24-323" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-324"><a href="#cb24-324" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>LastSeen <span class="ot">=</span><span class="fu">as.integer</span>(<span class="fu">difftime</span>(<span class="fu">max</span>(data<span class="sc">$</span>InvoiceDate), data<span class="sc">$</span>InvoiceDate, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb24-325"><a href="#cb24-325" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-326"><a href="#cb24-326" aria-hidden="true" tabindex="-1"></a>customer_lastseen <span class="ot">&lt;-</span>  <span class="fu">as.data.frame</span>(data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(CustomerID) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">LastSeen =</span> <span class="fu">min</span>(LastSeen)))</span>
<span id="cb24-327"><a href="#cb24-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-328"><a href="#cb24-328" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-329"><a href="#cb24-329" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Merge the above data frames to get unique customer and their total amount, frequency of visit to the store and the LastSeen shopping in the store</span>
<span id="cb24-330"><a href="#cb24-330" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-331"><a href="#cb24-331" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-332"><a href="#cb24-332" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">merge</span>(customer_monetary, customer_frequency, <span class="at">by =</span> <span class="st">'CustomerID'</span>)</span>
<span id="cb24-333"><a href="#cb24-333" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">merge</span>(customer, customer_lastseen, <span class="at">by =</span> <span class="st">'CustomerID'</span>)</span>
<span id="cb24-334"><a href="#cb24-334" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-335"><a href="#cb24-335" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-336"><a href="#cb24-336" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Detect outliers and remove them. To create meaningful clusters, we will be removing outliers from  numeric columns Amount, Invoice and LastSeen</span>
<span id="cb24-337"><a href="#cb24-337" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-338"><a href="#cb24-338" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE, message=FALSE}</span></span>
<span id="cb24-339"><a href="#cb24-339" aria-hidden="true" tabindex="-1"></a><span class="fu">melt</span>(customer[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>variable, <span class="at">y=</span>value)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>variable), <span class="at">outlier.colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span>
<span id="cb24-340"><a href="#cb24-340" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-341"><a href="#cb24-341" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-342"><a href="#cb24-342" aria-hidden="true" tabindex="-1"></a>Above graph shows that there are outliers that need to be addressed to get accurate clustering results.</span>
<span id="cb24-343"><a href="#cb24-343" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-344"><a href="#cb24-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-345"><a href="#cb24-345" aria-hidden="true" tabindex="-1"></a><span class="co"># create detect outlier function</span></span>
<span id="cb24-346"><a href="#cb24-346" aria-hidden="true" tabindex="-1"></a>detect_outlier <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb24-347"><a href="#cb24-347" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate first quantile</span></span>
<span id="cb24-348"><a href="#cb24-348" aria-hidden="true" tabindex="-1"></a>    Quantile1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span>.<span class="dv">25</span>)</span>
<span id="cb24-349"><a href="#cb24-349" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate third quantile</span></span>
<span id="cb24-350"><a href="#cb24-350" aria-hidden="true" tabindex="-1"></a>    Quantile3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span>.<span class="dv">75</span>)</span>
<span id="cb24-351"><a href="#cb24-351" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate inter quartile range</span></span>
<span id="cb24-352"><a href="#cb24-352" aria-hidden="true" tabindex="-1"></a>    IQR <span class="ot">=</span> Quantile3<span class="sc">-</span>Quantile1</span>
<span id="cb24-353"><a href="#cb24-353" aria-hidden="true" tabindex="-1"></a>    <span class="co"># return true or false</span></span>
<span id="cb24-354"><a href="#cb24-354" aria-hidden="true" tabindex="-1"></a>    x <span class="sc">&gt;</span> Quantile3 <span class="sc">+</span> (IQR<span class="sc">*</span><span class="fl">1.5</span>) <span class="sc">|</span> x <span class="sc">&lt;</span> Quantile1 <span class="sc">-</span> (IQR<span class="sc">*</span><span class="fl">1.5</span>)</span>
<span id="cb24-355"><a href="#cb24-355" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-356"><a href="#cb24-356" aria-hidden="true" tabindex="-1"></a><span class="co"># create remove outlier function</span></span>
<span id="cb24-357"><a href="#cb24-357" aria-hidden="true" tabindex="-1"></a>remove_outlier <span class="ot">&lt;-</span> <span class="cf">function</span>(dataframe,</span>
<span id="cb24-358"><a href="#cb24-358" aria-hidden="true" tabindex="-1"></a>                            <span class="at">columns=</span><span class="fu">names</span>(dataframe)) {</span>
<span id="cb24-359"><a href="#cb24-359" aria-hidden="true" tabindex="-1"></a>    <span class="co"># for loop to traverse in columns vector</span></span>
<span id="cb24-360"><a href="#cb24-360" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (col <span class="cf">in</span> columns) {</span>
<span id="cb24-361"><a href="#cb24-361" aria-hidden="true" tabindex="-1"></a>        <span class="co"># remove observation if it satisfies outlier function</span></span>
<span id="cb24-362"><a href="#cb24-362" aria-hidden="true" tabindex="-1"></a>        dataframe <span class="ot">&lt;-</span> dataframe[<span class="sc">!</span><span class="fu">detect_outlier</span>(dataframe[[col]]), ]</span>
<span id="cb24-363"><a href="#cb24-363" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb24-364"><a href="#cb24-364" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(dataframe)</span>
<span id="cb24-365"><a href="#cb24-365" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-366"><a href="#cb24-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-367"><a href="#cb24-367" aria-hidden="true" tabindex="-1"></a><span class="co"># detect_outlier(customer$Amount)</span></span>
<span id="cb24-368"><a href="#cb24-368" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span> <span class="fu">remove_outlier</span>(customer, <span class="fu">c</span>(<span class="st">'Amount'</span>,<span class="st">'Frequency'</span>,<span class="st">'LastSeen'</span>))</span>
<span id="cb24-369"><a href="#cb24-369" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-370"><a href="#cb24-370" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-371"><a href="#cb24-371" aria-hidden="true" tabindex="-1"></a>Now, after removing outliers and cleaning up the data, we see normal distribution of the Amount, Frequency and LastSeen columns.</span>
<span id="cb24-372"><a href="#cb24-372" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-373"><a href="#cb24-373" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE, message=FALSE}</span></span>
<span id="cb24-374"><a href="#cb24-374" aria-hidden="true" tabindex="-1"></a><span class="fu">melt</span>(customer[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>variable, <span class="at">y=</span>value)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>variable), <span class="at">outlier.colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span>
<span id="cb24-375"><a href="#cb24-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-376"><a href="#cb24-376" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-377"><a href="#cb24-377" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Scale the data. Since K-Means utilizes the proximity of data points based on Euclidean distance, it is important to reconcile all dimensions into a standard scale.</span>
<span id="cb24-378"><a href="#cb24-378" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-379"><a href="#cb24-379" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-380"><a href="#cb24-380" aria-hidden="true" tabindex="-1"></a>customer_details <span class="ot">&lt;-</span> customer</span>
<span id="cb24-381"><a href="#cb24-381" aria-hidden="true" tabindex="-1"></a>customer <span class="ot">&lt;-</span>  customer <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>CustomerID)</span>
<span id="cb24-382"><a href="#cb24-382" aria-hidden="true" tabindex="-1"></a><span class="co"># scale numeric attributes</span></span>
<span id="cb24-383"><a href="#cb24-383" aria-hidden="true" tabindex="-1"></a>customer_scaled <span class="ot">&lt;-</span> customer <span class="sc">%&gt;%</span> <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"Amount"</span>, <span class="st">"Frequency"</span>, <span class="st">"LastSeen"</span>), <span class="sc">~</span>(<span class="fu">scale</span>(.) <span class="sc">%&gt;%</span> as.vector))</span>
<span id="cb24-384"><a href="#cb24-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-385"><a href="#cb24-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-386"><a href="#cb24-386" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-387"><a href="#cb24-387" aria-hidden="true" tabindex="-1"></a><span class="fu">## Target Dataset Analysis</span></span>
<span id="cb24-388"><a href="#cb24-388" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-389"><a href="#cb24-389" aria-hidden="true" tabindex="-1"></a>We started our analysis with total 525461 records but after preparing and cleansing the data, we are left with total 3674 records to be analyzed.</span>
<span id="cb24-390"><a href="#cb24-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-391"><a href="#cb24-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-392"><a href="#cb24-392" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, warning=FALSE, results = "asis"}</span></span>
<span id="cb24-393"><a href="#cb24-393" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-394"><a href="#cb24-394" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">vars =</span> <span class="fu">c</span>(<span class="st">'CustomerID'</span>, <span class="st">'Amount'</span>, <span class="st">'Frequency'</span>, <span class="st">'LastSeen'</span>),               </span>
<span id="cb24-395"><a href="#cb24-395" aria-hidden="true" tabindex="-1"></a>                <span class="at">DataType =</span> <span class="fu">c</span>(<span class="st">'Numeric'</span>, <span class="st">'Numeric'</span>, <span class="st">'Numeric'</span>, <span class="st">'Numeric'</span>),</span>
<span id="cb24-396"><a href="#cb24-396" aria-hidden="true" tabindex="-1"></a>                <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">'Customer number. A 5-digit integral number uniquely assigned to each customer.'</span>,</span>
<span id="cb24-397"><a href="#cb24-397" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Total Amount spent by each unique customer'</span>,</span>
<span id="cb24-398"><a href="#cb24-398" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Number of times customer made purchases bases on their invoice.'</span>,</span>
<span id="cb24-399"><a href="#cb24-399" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Days elapsed since the customer was last seen shopping.'</span>),</span>
<span id="cb24-400"><a href="#cb24-400" aria-hidden="true" tabindex="-1"></a>                <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-401"><a href="#cb24-401" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-402"><a href="#cb24-402" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(a,</span>
<span id="cb24-403"><a href="#cb24-403" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Target Data Definition"</span>,</span>
<span id="cb24-404"><a href="#cb24-404" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Attribute"</span>, <span class="st">"Type"</span>, <span class="st">"Description"</span>),</span>
<span id="cb24-405"><a href="#cb24-405" aria-hidden="true" tabindex="-1"></a>      <span class="at">align=</span><span class="st">"lcl"</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-406"><a href="#cb24-406" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-407"><a href="#cb24-407" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> T, <span class="at">background =</span> <span class="st">"#666666"</span>, <span class="at">color =</span> <span class="st">"white"</span>)</span>
<span id="cb24-408"><a href="#cb24-408" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-409"><a href="#cb24-409" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-410"><a href="#cb24-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-411"><a href="#cb24-411" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, warning=FALSE, results = "asis"}</span></span>
<span id="cb24-412"><a href="#cb24-412" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">vars =</span> <span class="fu">c</span>(<span class="st">'Amount'</span>, <span class="st">'Frequency'</span>, <span class="st">'LastSeen'</span>),                       </span>
<span id="cb24-413"><a href="#cb24-413" aria-hidden="true" tabindex="-1"></a>                <span class="at">Mean =</span> <span class="fu">c</span>(<span class="st">'776.5'</span>, <span class="st">'48.15'</span>, <span class="st">'101.8'</span>),             </span>
<span id="cb24-414"><a href="#cb24-414" aria-hidden="true" tabindex="-1"></a>                <span class="at">Min =</span> <span class="fu">c</span>(<span class="st">'-1598.7'</span>,<span class="st">'1'</span>,<span class="st">'0'</span>),</span>
<span id="cb24-415"><a href="#cb24-415" aria-hidden="true" tabindex="-1"></a>                <span class="at">Q1 =</span> <span class="fu">c</span>(<span class="st">'241.5'</span>, <span class="st">'15.0'</span>, <span class="st">'23.0'</span>),</span>
<span id="cb24-416"><a href="#cb24-416" aria-hidden="true" tabindex="-1"></a>                <span class="at">Median =</span> <span class="fu">c</span>(<span class="st">'515.1'</span>, <span class="st">'34.0'</span>, <span class="st">'62.0'</span>),</span>
<span id="cb24-417"><a href="#cb24-417" aria-hidden="true" tabindex="-1"></a>                <span class="at">Q3 =</span> <span class="fu">c</span>(<span class="st">'1091.4'</span>, <span class="st">'70.0'</span>, <span class="st">'163.0'</span>),</span>
<span id="cb24-418"><a href="#cb24-418" aria-hidden="true" tabindex="-1"></a>                <span class="at">Max =</span> <span class="fu">c</span>(<span class="st">'3685.1'</span>, <span class="st">'183.0'</span>,<span class="st">'373.0'</span>),</span>
<span id="cb24-419"><a href="#cb24-419" aria-hidden="true" tabindex="-1"></a>                <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-420"><a href="#cb24-420" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-421"><a href="#cb24-421" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(a,</span>
<span id="cb24-422"><a href="#cb24-422" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Summary of Target Dataset (3674 Records)"</span>,</span>
<span id="cb24-423"><a href="#cb24-423" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"Mean"</span>,<span class="st">"Min"</span>, <span class="st">"Q1"</span>, <span class="st">"Median"</span>, <span class="st">"Q3"</span>, <span class="st">"Max"</span>),</span>
<span id="cb24-424"><a href="#cb24-424" aria-hidden="true" tabindex="-1"></a>      <span class="at">align=</span><span class="st">"lcc"</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-425"><a href="#cb24-425" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-426"><a href="#cb24-426" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> T, <span class="at">background =</span> <span class="st">"#666666"</span>, <span class="at">color =</span> <span class="st">"white"</span>)</span>
<span id="cb24-427"><a href="#cb24-427" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-428"><a href="#cb24-428" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-429"><a href="#cb24-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-430"><a href="#cb24-430" aria-hidden="true" tabindex="-1"></a><span class="fu">## Statistical Modeling</span></span>
<span id="cb24-431"><a href="#cb24-431" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-432"><a href="#cb24-432" aria-hidden="true" tabindex="-1"></a><span class="fu">### Optimal Number of Clusters (K)</span></span>
<span id="cb24-433"><a href="#cb24-433" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-434"><a href="#cb24-434" aria-hidden="true" tabindex="-1"></a>One of the challenges in the K-Means clustering is determining initial value of K to ensure the resulting solution actually represents the underlying structure in the data. The reliability and the performance of a clustering algorithm is directly affected by the initial choice of the number of clusters (K).</span>
<span id="cb24-435"><a href="#cb24-435" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-436"><a href="#cb24-436" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Elbow Method</span></span>
<span id="cb24-437"><a href="#cb24-437" aria-hidden="true" tabindex="-1"></a>We will be using a popular method called *Elbow Method* to determine the optimal value of K. The underlying idea behind this method is that it calculates values of cost with changing K. As the value of K increases, the cluster will have fewer data points and the distortion (within cluster sum of square) will decrease. The larger number of clusters (and hence the lesser number of data points within the cluster) implies the data points are closer to the centroid. So, the point where this distortion declines the most is the elbow point.<span class="co">[</span><span class="ot">@ste2011Choosing</span><span class="co">]</span></span>
<span id="cb24-438"><a href="#cb24-438" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-439"><a href="#cb24-439" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-440"><a href="#cb24-440" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(customer_scaled, kmeans, <span class="at">method =</span> <span class="st">"wss"</span>) <span class="sc">+</span></span>
<span id="cb24-441"><a href="#cb24-441" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">3</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb24-442"><a href="#cb24-442" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Elbow Method"</span>)</span>
<span id="cb24-443"><a href="#cb24-443" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-444"><a href="#cb24-444" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-445"><a href="#cb24-445" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Silhouette Method</span></span>
<span id="cb24-446"><a href="#cb24-446" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-447"><a href="#cb24-447" aria-hidden="true" tabindex="-1"></a>Another way to find the optimal number of clusters in K-Means is Silhouette Method. We will be using it to double check the results we obtained from the above Elbow method.</span>
<span id="cb24-448"><a href="#cb24-448" aria-hidden="true" tabindex="-1"></a>The silhouette method calculates a coefficient (called silhouette coefficient) which is a measure of how similar a data point is within-cluster (cohesion) compared to other clusters (separation).<span class="co">[</span><span class="ot">@li2013application</span><span class="co">]</span></span>
<span id="cb24-449"><a href="#cb24-449" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-450"><a href="#cb24-450" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-451"><a href="#cb24-451" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(customer_scaled, kmeans, <span class="at">method =</span> <span class="st">"silhouette"</span>)<span class="sc">+</span> <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb24-452"><a href="#cb24-452" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Silhouette Method"</span>)</span>
<span id="cb24-453"><a href="#cb24-453" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-454"><a href="#cb24-454" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-455"><a href="#cb24-455" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Gap Statistic Method</span></span>
<span id="cb24-456"><a href="#cb24-456" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-457"><a href="#cb24-457" aria-hidden="true" tabindex="-1"></a>The basic idea of the Gap Statistics is to choose the number of K, where the biggest jump in within-cluster distance occurred, based on the overall behavior of uniformly drawn samples.<span class="co">[</span><span class="ot">@tibs2001Gap</span><span class="co">]</span></span>
<span id="cb24-458"><a href="#cb24-458" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-459"><a href="#cb24-459" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-460"><a href="#cb24-460" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-461"><a href="#cb24-461" aria-hidden="true" tabindex="-1"></a>gap_stat <span class="ot">&lt;-</span> <span class="fu">clusGap</span>(customer_scaled, <span class="at">FUN =</span> kmeans, <span class="at">nstart =</span> <span class="dv">25</span>, <span class="at">K.max =</span> <span class="dv">10</span>, <span class="at">B =</span> <span class="dv">50</span>)</span>
<span id="cb24-462"><a href="#cb24-462" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-463"><a href="#cb24-463" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_gap_stat</span>(gap_stat)</span>
<span id="cb24-464"><a href="#cb24-464" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-465"><a href="#cb24-465" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-466"><a href="#cb24-466" aria-hidden="true" tabindex="-1"></a>From the above graphs for Elbow, Silhouette and Gap Statistics methods, we can observe the critical point is at '3'. So, we will pick 3 as our k value for number of clusters.</span>
<span id="cb24-467"><a href="#cb24-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-468"><a href="#cb24-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-469"><a href="#cb24-469" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-470"><a href="#cb24-470" aria-hidden="true" tabindex="-1"></a>K = 3</span>
<span id="cb24-471"><a href="#cb24-471" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb24-472"><a href="#cb24-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-473"><a href="#cb24-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-474"><a href="#cb24-474" aria-hidden="true" tabindex="-1"></a><span class="fu">### K-Means Model</span></span>
<span id="cb24-475"><a href="#cb24-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-476"><a href="#cb24-476" aria-hidden="true" tabindex="-1"></a>Now, we will create the K-Means model with K = 3.</span>
<span id="cb24-477"><a href="#cb24-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-478"><a href="#cb24-478" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-479"><a href="#cb24-479" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute k-means with k = 3</span></span>
<span id="cb24-480"><a href="#cb24-480" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-481"><a href="#cb24-481" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb24-482"><a href="#cb24-482" aria-hidden="true" tabindex="-1"></a>m1.kmean <span class="ot">&lt;-</span> customer_scaled <span class="sc">%&gt;%</span> <span class="fu">kmeans</span>(k, <span class="at">iter.max =</span> <span class="dv">20</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb24-483"><a href="#cb24-483" aria-hidden="true" tabindex="-1"></a><span class="co">#nstart option that attempts multiple initial configurations and reports on the best one</span></span>
<span id="cb24-484"><a href="#cb24-484" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-485"><a href="#cb24-485" aria-hidden="true" tabindex="-1"></a><span class="co">#Add Clusters to the original dataframe</span></span>
<span id="cb24-486"><a href="#cb24-486" aria-hidden="true" tabindex="-1"></a>customer<span class="sc">$</span>Cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(m1.kmean<span class="sc">$</span>cluster)</span>
<span id="cb24-487"><a href="#cb24-487" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-488"><a href="#cb24-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-489"><a href="#cb24-489" aria-hidden="true" tabindex="-1"></a>The model results in 3 clusters as was decided and the clusters are formed with sizes 1807, 953, 914.</span>
<span id="cb24-490"><a href="#cb24-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-491"><a href="#cb24-491" aria-hidden="true" tabindex="-1"></a>Now, we can extract the clusters and add to our initial data to do some descriptive statistics at the cluster level. Below table summarizes the original dataset grouped by clusters to show the mean of the variables:</span>
<span id="cb24-492"><a href="#cb24-492" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-493"><a href="#cb24-493" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-494"><a href="#cb24-494" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-495"><a href="#cb24-495" aria-hidden="true" tabindex="-1"></a>clustStats <span class="ot">&lt;-</span> customer <span class="sc">%&gt;%</span></span>
<span id="cb24-496"><a href="#cb24-496" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Cluster) <span class="sc">%&gt;%</span></span>
<span id="cb24-497"><a href="#cb24-497" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="st">"mean"</span>)</span>
<span id="cb24-498"><a href="#cb24-498" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-499"><a href="#cb24-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-500"><a href="#cb24-500" aria-hidden="true" tabindex="-1"></a>clustStats <span class="sc">%&gt;%</span></span>
<span id="cb24-501"><a href="#cb24-501" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-502"><a href="#cb24-502" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_paper</span>(<span class="st">"hover"</span>, <span class="at">full_width =</span> T)</span>
<span id="cb24-503"><a href="#cb24-503" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-504"><a href="#cb24-504" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-505"><a href="#cb24-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-506"><a href="#cb24-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-507"><a href="#cb24-507" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-508"><a href="#cb24-508" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,</span>
<span id="cb24-509"><a href="#cb24-509" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb24-510"><a href="#cb24-510" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb24-511"><a href="#cb24-511" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb24-512"><a href="#cb24-512" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb24-513"><a href="#cb24-513" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-514"><a href="#cb24-514" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-515"><a href="#cb24-515" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-516"><a href="#cb24-516" aria-hidden="true" tabindex="-1"></a>The above graph shows the clusters created using all columns of customer dataframe using the first two principle components to define the X-Y coordinates of each observation.</span>
<span id="cb24-517"><a href="#cb24-517" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-518"><a href="#cb24-518" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-519"><a href="#cb24-519" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-520"><a href="#cb24-520" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"LastSeen"</span>,<span class="st">"Amount"</span>),</span>
<span id="cb24-521"><a href="#cb24-521" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb24-522"><a href="#cb24-522" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb24-523"><a href="#cb24-523" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb24-524"><a href="#cb24-524" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb24-525"><a href="#cb24-525" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb24-526"><a href="#cb24-526" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-527"><a href="#cb24-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-528"><a href="#cb24-528" aria-hidden="true" tabindex="-1"></a>The above graph shows that the clusters 1 and 3 are seen in the store often. Cluster 3 customers are spending more whenever they visit. Cluster 2 not seen recently so spend less.</span>
<span id="cb24-529"><a href="#cb24-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-530"><a href="#cb24-530" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-531"><a href="#cb24-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-532"><a href="#cb24-532" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"Frequency"</span>,<span class="st">"Amount"</span>),</span>
<span id="cb24-533"><a href="#cb24-533" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>),</span>
<span id="cb24-534"><a href="#cb24-534" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb24-535"><a href="#cb24-535" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,</span>
<span id="cb24-536"><a href="#cb24-536" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb24-537"><a href="#cb24-537" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb24-538"><a href="#cb24-538" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-539"><a href="#cb24-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-540"><a href="#cb24-540" aria-hidden="true" tabindex="-1"></a>The above graph shows that the Cluster 3 are more frequently buying and hence spending more. Cluster 1 and 2 are almost having similar trends in terms of number of purchases and amount spent.</span>
<span id="cb24-541"><a href="#cb24-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-542"><a href="#cb24-542" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-543"><a href="#cb24-543" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(m1.kmean, <span class="at">data =</span> customer_scaled,<span class="at">choose.vars =</span> <span class="fu">c</span>(<span class="st">"LastSeen"</span>,<span class="st">"Frequency"</span>),</span>
<span id="cb24-544"><a href="#cb24-544" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#2E9FDF"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>), </span>
<span id="cb24-545"><a href="#cb24-545" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb24-546"><a href="#cb24-546" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"convex"</span>, </span>
<span id="cb24-547"><a href="#cb24-547" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb24-548"><a href="#cb24-548" aria-hidden="true" tabindex="-1"></a>             )       </span>
<span id="cb24-549"><a href="#cb24-549" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-550"><a href="#cb24-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-551"><a href="#cb24-551" aria-hidden="true" tabindex="-1"></a>The above graph shows that the Cluster 1 and 3 are seen buying often and whenever they are seen buying, they make lot of purchases.</span>
<span id="cb24-552"><a href="#cb24-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-553"><a href="#cb24-553" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-554"><a href="#cb24-554" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#9f00e6"</span>, <span class="st">"#e69f00"</span>, <span class="st">"#00e69f"</span>)</span>
<span id="cb24-555"><a href="#cb24-555" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> colors[<span class="fu">as.numeric</span>(m1.kmean<span class="sc">$</span>cluster)]</span>
<span id="cb24-556"><a href="#cb24-556" aria-hidden="true" tabindex="-1"></a>s3d <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(customer_scaled, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">color=</span>colors)</span>
<span id="cb24-557"><a href="#cb24-557" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"top"</span>,<span class="at">legend =</span> <span class="fu">paste</span>(<span class="st">"Cluster"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb24-558"><a href="#cb24-558" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span>  <span class="fu">c</span>(<span class="st">"#9f00e6"</span>, <span class="st">"#e69f00"</span>, <span class="st">"#00e69f"</span>), <span class="at">pch =</span> <span class="dv">16</span>)    </span>
<span id="cb24-559"><a href="#cb24-559" aria-hidden="true" tabindex="-1"></a>centers <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(m1.kmean<span class="sc">$</span>centers)</span>
<span id="cb24-560"><a href="#cb24-560" aria-hidden="true" tabindex="-1"></a>s3dp <span class="ot">&lt;-</span> s3d<span class="sc">$</span><span class="fu">points3d</span>(centers,</span>
<span id="cb24-561"><a href="#cb24-561" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#000000"</span>,<span class="st">"#0e0a00"</span>,<span class="st">"#000e0a"</span>), <span class="at">type =</span> <span class="st">"h"</span>, <span class="at">pch =</span> <span class="dv">8</span>)</span>
<span id="cb24-562"><a href="#cb24-562" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-563"><a href="#cb24-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-564"><a href="#cb24-564" aria-hidden="true" tabindex="-1"></a>From the above graph that depicts all the three dimensions of the clustering, we can clearly see that the customers in cluster 3 are seen shopping often, they spend more, and they purchase frequently.</span>
<span id="cb24-565"><a href="#cb24-565" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-566"><a href="#cb24-566" aria-hidden="true" tabindex="-1"></a>Customers in cluster 2 are of concern. They do not visit the website often but spend almost similar to cluster 1 and also purchase as frequently as cluster 1. So, we can either target cluster 1 to make them buy when they visit store (since they are visiting often but buying less) or make cluster 2 visit often as they are buying more when they visit but visiting less.</span>
<span id="cb24-567"><a href="#cb24-567" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-568"><a href="#cb24-568" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-569"><a href="#cb24-569" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>Amount, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()<span class="sc">+</span>  <span class="fu">theme_classic</span>()  <span class="sc">+</span> </span>
<span id="cb24-570"><a href="#cb24-570" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on Amount Spent"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span>
<span id="cb24-571"><a href="#cb24-571" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-572"><a href="#cb24-572" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-573"><a href="#cb24-573" aria-hidden="true" tabindex="-1"></a>Customers in Cluster# 3 are spending more whereas cluster 2 customers are spending the least.</span>
<span id="cb24-574"><a href="#cb24-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-575"><a href="#cb24-575" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-576"><a href="#cb24-576" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>Frequency, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb24-577"><a href="#cb24-577" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on Number of transactions"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span>
<span id="cb24-578"><a href="#cb24-578" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-579"><a href="#cb24-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-580"><a href="#cb24-580" aria-hidden="true" tabindex="-1"></a>Customers in Cluster# 3 are most frequent customers indicating that the frequent customers spend  the most.</span>
<span id="cb24-581"><a href="#cb24-581" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-582"><a href="#cb24-582" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, echo=TRUE}</span></span>
<span id="cb24-583"><a href="#cb24-583" aria-hidden="true" tabindex="-1"></a>customer <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Cluster, <span class="at">y=</span>LastSeen, <span class="at">fill=</span>Cluster)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb24-584"><a href="#cb24-584" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Clusters based on customer last seen shopping"</span>, <span class="at">subtitle =</span> <span class="st">"K-Means Model m1.kmeans"</span>)</span>
<span id="cb24-585"><a href="#cb24-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-586"><a href="#cb24-586" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-587"><a href="#cb24-587" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-588"><a href="#cb24-588" aria-hidden="true" tabindex="-1"></a>Customers in Cluster 2 have not been seen shopping recently. The most recently seen shoppers are in Cluster 3 and that also explains why they have spent more money and bought frequently.</span>
<span id="cb24-589"><a href="#cb24-589" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-590"><a href="#cb24-590" aria-hidden="true" tabindex="-1"></a><span class="fu">### Analysis</span></span>
<span id="cb24-591"><a href="#cb24-591" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-592"><a href="#cb24-592" aria-hidden="true" tabindex="-1"></a><span class="al">![Image Source: ©Anand](RFM.png)</span></span>
<span id="cb24-593"><a href="#cb24-593" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-594"><a href="#cb24-594" aria-hidden="true" tabindex="-1"></a>For this business, it is a matter of concern that most of their customers (49%) are not finding what they want. The shop would need to revisit their strategy of what brand/item they should be selling in the online shop to convert visits into revenue.</span>
<span id="cb24-595"><a href="#cb24-595" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-596"><a href="#cb24-596" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb24-597"><a href="#cb24-597" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb24-598"><a href="#cb24-598" aria-hidden="true" tabindex="-1"></a> For businesses, the customer segmentation play pivotal role in identifying the customers by grouping them based on their buying habits and patterns. With increasingly large volume of transactions and unprecedented business activities, a clustering algorithm like K-Means is a great tool to achieve the segmentation of customers with speed and accuracy. In this paper, we have tried a real-time online business data to show how K-Means helped the business in identifying customers who are at risk of switching to other stores. We have also explained that there are multiple steps in the data mining processes and it started with data selection, then to data preparation, visualization, and finally to model creation and interpretation. </span>
<span id="cb24-599"><a href="#cb24-599" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-600"><a href="#cb24-600" aria-hidden="true" tabindex="-1"></a> We also understand that K-Means is not always accurate and is dependent on initial choice of centroids and optimal number of clusters chosen. However, there are some improved algorithms that can help overcome these shortcomings.</span>
<span id="cb24-601"><a href="#cb24-601" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-602"><a href="#cb24-602" aria-hidden="true" tabindex="-1"></a><span class="fu"># References</span></span>
<span id="cb24-603"><a href="#cb24-603" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-604"><a href="#cb24-604" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-605"><a href="#cb24-605" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-606"><a href="#cb24-606" aria-hidden="true" tabindex="-1"></a> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>